
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.13-stretch
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:6.13-stretch
    steps:
      - checkout
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
