---
AWSTemplateFormatVersion: '2010-09-09'
Description: Handel EFS Mount
Parameters:
  EfsMountTargetSubnets:
    Description: A comma delimited list of subnets for the EFS mount targets
    Type: CommaDelimitedList
  Ec2SecurityGroup:
    Description: The ID of the Ec2 security group
    Type: String
  VpcId:
    Description: ID of the VPC
    Type: String
Resources:
  EfsFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
      - Key: Name
        Value: handel-codepipeline-worker
  EfsMountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The security group for the EFS mount targets 
      VpcId:
        Ref: VpcId
  EfsMountTargetSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: EfsMountTargetSecurityGroup
      IpProtocol: tcp
      FromPort: 2049
      ToPort: 2049
      SourceSecurityGroupId:
        Ref: Ec2SecurityGroup
  EfsMountAvailA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: EfsFileSystem
      SecurityGroups:
      - Ref: EfsMountTargetSecurityGroup
      SubnetId: !Select ["0", !Ref EfsMountTargetSubnets]
  EfsMountAvailB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: EfsFileSystem
      SecurityGroups:
      - Ref: EfsMountTargetSecurityGroup
      SubnetId: !Select ["1", !Ref EfsMountTargetSubnets]
Outputs:
  EfsId:
    Description: The ID of the EFS mount
    Value: !Ref EfsFileSystem
